services:
  redis:
    image: redis:8

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  migration_db:
    build:
      context: ../..
      dockerfile: src/controller/Dockerfile.api

    image: cron-api:latest

    depends_on:
      redis:
        condition: service_healthy

    env_file:
      - ../infra/core/.env

    environment:
      redis_host: redis
      redis_port: "6379"

    command:
      - python
      - -m
      - src.infra.manage
      - migration_db

    restart: "no"

  migration_redis:
    build:
      context: ../..
      dockerfile: src/controller/Dockerfile.api

    image: cron-api:latest

    depends_on:
      redis:
        condition: service_healthy
      migration_db:
        condition: service_completed_successfully

    env_file:
      - ../infra/core/.env

    environment:
      redis_host: redis
      redis_port: "6379"

    command:
      - python
      - -m
      - src.infra.manage
      - migration_redis

    restart: "no"
   
  api:
    build:
      context: ../..
      dockerfile: src/controller/Dockerfile.api

    image: cron-api:latest

    depends_on:
      redis:
        condition: service_healthy
      migration_redis:
        condition: service_completed_successfully

    env_file:
      - ../infra/core/.env

    environment:
      redis_host: redis
      redis_port: "6379"

    ports:
      - "8000:8000"

    command:
      - python
      - -m
      - uvicorn
      - src.aplication.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    
  worker:
    build: 
      context: ../..
      dockerfile: src/controller/Dockerfile.worker

    image: cron-worker:latest

    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started

    env_file:
      - ../infra/core/.env
  
  cron:
    build: 
      context: ../..
      dockerfile: src/controller/Dockerfile.cron

    image: cron-loop:latest

    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started
      worker:
        condition: service_started

    env_file:
      - ../infra/core/.env

  nginx:
    image: nginx:alpine
    depends_on:
      -  api
    ports:
      - "8080:8080"

    volumes:
      - ./server.conf:/etc/nginx/nginx.conf:ro
