worker_processes auto;

events { 
    worker_connections 2024;
 };

 http { 
    server { 
        listen 8080;

        location  /requests/ {
            proxy_pass http://127.0.0.1:8000;
            
        }
        location /tasks/ {
            proxy_pass http://127.0.0.1:8000;
            
        }
     };
    

 };